version: "3.7"

services:
  web:
    container_name: web
    image: tutum/hello-world:${DOCKER_TAG}
    environment:
      VIRTUAL_HOST: ${DOMAINS}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: ${DOMAINS}
    env_file:
      - ./.env
    networks:
      - reverse_proxy


networks:
  reverse_proxy:
    name: reverse_proxy